# Generated by Django 5.1.4 on 2025-02-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fotoprofle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoprofle',
            name='gambar_profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
