# Generated by Django 5.2 on 2025-05-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fotoProfile',
        ),
    ]
