# Generated by Django 5.2 on 2025-05-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_fotoprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
