# Generated by Django 5.2 on 2025-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_profile_nama_lengkap'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
