# Generated by Django 5.2 on 2025-06-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_profile_total_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='total_points',
            new_name='points',
        ),
    ]
